### ISSUE TITLE
various operations fail with method not found error: 'net.sf.saxon.s9api.XdmSequenceIterator net.sf.saxon.s9api.XdmValue.iterator()'

### ISSUE THREAD

**Issue by lueck** [SCDH/oxbytei#10]
Various operations fail with an error message similar to the one below.

Oxygen: 24.1
oxbytei: 0.17.0

```
The application detected an error that is not automatically handled. It is possible that this error is not critical and the application may continue to work normally but our recommendation is to report the error and restart the application. If the application has become unstable and cannot be closed normally, you can use the Force Quit button from this dialog. Be aware that by doing this you will lose all unsaved changes in the opened documents.

Here are the error details:

[ AWT-EventQueue-0 ]  -  Couldn't execute operation: 'de.wwu.scdh.oxbytei.SelectAttributeValueOperation' for action: 'Select tag' because of: 'net.sf.saxon.s9api.XdmSequenceIterator net.sf.saxon.s9api.XdmValue.iterator()'
java.lang.NoSuchMethodError: 'net.sf.saxon.s9api.XdmSequenceIterator net.sf.saxon.s9api.XdmValue.iterator()'
        at de.wwu.scdh.teilsp.extensions.AbstractLabelledEntriesX.getEntries(AbstractLabelledEntriesX.java:62)
        at de.wwu.scdh.teilsp.extensions.LabelledEntriesXSLT.getLabelledEntries(LabelledEntriesXSLT.java:178)
        at de.wwu.scdh.teilsp.ui.CheckBoxSelectDialog.doUserInteraction(CheckBoxSelectDialog.java:154)
        at de.wwu.scdh.oxbytei.SelectLabelledEntryInteraction.doUserInteraction(SelectLabelledEntryInteraction.java:321)
        at de.wwu.scdh.oxbytei.SelectAttributeValueOperation.doOperation(SelectAttributeValueOperation.java:85)
        at ro.sync.ecss.extensions.o.h(Unknown Source)
        at ro.sync.ecss.extensions.o.b(Unknown Source)
        at ro.sync.ecss.extensions.o.d(Unknown Source)
        at ro.sync.ecss.extensions.j.d(Unknown Source)
        at ro.sync.ecss.extensions.j.y(Unknown Source)
        at ro.sync.ecss.extensions.j.performAction(Unknown Source)
        at ro.sync.ecss.component.editor.y$4$1.run(Unknown Source)
        at ro.sync.ui.ve$_b.run(Unknown Source)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by lueck** [comment]
oXbytei's Java classes depend on Saxon. oXygen also depends on Saxon and every version ships with an other version of Saxon. Saxon's API evolves from major version to major version (9.x.x.x ... 12.x.x.x). That's why we offer oXbytei built (compiled) for different versions of oXygen: The builds are compiled against different versions of Saxon.

oXbytei build for oXygen 24 and 24.1 expect that Saxon 10.x (10.6) is used. You can check which version ships with your oXygen under the menu **Help** -> **About** -> **Libraries**.

- oXygen 23, 23.1: Saxon EE 9.9.1-7
- oXygen 24, 24.1: Saxon EE 10.6
- oXygen 25, 25.1: Saxon EE 11.2
- oXygen 26+: Saxon EE 12.3

**Comment by lueck** [comment]
In the case reported, it was an installation of oXygen 24.1, but it used Saxon EE 9.9.x. So the installed build of oXbytei was compiled against an other version of Saxon than the one in use.

Uninstalling oXygen and re-installing oXygen 24.1 as shipped in the [software archive](https://www.oxygenxml.com/xml_editor/software_archive_editor.html) solved the issue.
